// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: internal/sfu/proto/sfu.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_sfu_proto_sfu_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_sfu_proto_sfu_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HealthCheckResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_sfu_proto_sfu_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type SessionDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "offer", "answer"
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // "publisher", "subscriber"
	Sdp           string                 `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionDescription) Reset() {
	*x = SessionDescription{}
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDescription) ProtoMessage() {}

func (x *SessionDescription) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDescription.ProtoReflect.Descriptor instead.
func (*SessionDescription) Descriptor() ([]byte, []int) {
	return file_internal_sfu_proto_sfu_proto_rawDescGZIP(), []int{3}
}

func (x *SessionDescription) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SessionDescription) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SessionDescription) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type IceCandidate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Role             string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "publisher", "subscriber"
	Candidate        string                 `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid           string                 `protobuf:"bytes,3,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex    int32                  `protobuf:"varint,4,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	UsernameFragment string                 `protobuf:"bytes,5,opt,name=username_fragment,json=usernameFragment,proto3" json:"username_fragment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IceCandidate) Reset() {
	*x = IceCandidate{}
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IceCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceCandidate) ProtoMessage() {}

func (x *IceCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceCandidate.ProtoReflect.Descriptor instead.
func (*IceCandidate) Descriptor() ([]byte, []int) {
	return file_internal_sfu_proto_sfu_proto_rawDescGZIP(), []int{4}
}

func (x *IceCandidate) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *IceCandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *IceCandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *IceCandidate) GetSdpMlineIndex() int32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

func (x *IceCandidate) GetUsernameFragment() string {
	if x != nil {
		return x.UsernameFragment
	}
	return ""
}

type Join struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Join) Reset() {
	*x = Join{}
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_internal_sfu_proto_sfu_proto_rawDescGZIP(), []int{5}
}

func (x *Join) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Join) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

type Leave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leave) Reset() {
	*x = Leave{}
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leave) ProtoMessage() {}

func (x *Leave) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leave.ProtoReflect.Descriptor instead.
func (*Leave) Descriptor() ([]byte, []int) {
	return file_internal_sfu_proto_sfu_proto_rawDescGZIP(), []int{6}
}

func (x *Leave) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Leave) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SignalRequest_Join
	//	*SignalRequest_Sdp
	//	*SignalRequest_Candidate
	//	*SignalRequest_Leave
	Payload       isSignalRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_internal_sfu_proto_sfu_proto_rawDescGZIP(), []int{7}
}

func (x *SignalRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SignalRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *SignalRequest) GetPayload() isSignalRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignalRequest) GetJoin() *Join {
	if x != nil {
		if x, ok := x.Payload.(*SignalRequest_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *SignalRequest) GetSdp() *SessionDescription {
	if x != nil {
		if x, ok := x.Payload.(*SignalRequest_Sdp); ok {
			return x.Sdp
		}
	}
	return nil
}

func (x *SignalRequest) GetCandidate() *IceCandidate {
	if x != nil {
		if x, ok := x.Payload.(*SignalRequest_Candidate); ok {
			return x.Candidate
		}
	}
	return nil
}

func (x *SignalRequest) GetLeave() *Leave {
	if x != nil {
		if x, ok := x.Payload.(*SignalRequest_Leave); ok {
			return x.Leave
		}
	}
	return nil
}

type isSignalRequest_Payload interface {
	isSignalRequest_Payload()
}

type SignalRequest_Join struct {
	Join *Join `protobuf:"bytes,3,opt,name=join,proto3,oneof"`
}

type SignalRequest_Sdp struct {
	Sdp *SessionDescription `protobuf:"bytes,4,opt,name=sdp,proto3,oneof"`
}

type SignalRequest_Candidate struct {
	Candidate *IceCandidate `protobuf:"bytes,5,opt,name=candidate,proto3,oneof"`
}

type SignalRequest_Leave struct {
	Leave *Leave `protobuf:"bytes,6,opt,name=leave,proto3,oneof"`
}

func (*SignalRequest_Join) isSignalRequest_Payload() {}

func (*SignalRequest_Sdp) isSignalRequest_Payload() {}

func (*SignalRequest_Candidate) isSignalRequest_Payload() {}

func (*SignalRequest_Leave) isSignalRequest_Payload() {}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SignalResponse_Sdp
	//	*SignalResponse_Candidate
	Payload       isSignalResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_proto_sfu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_internal_sfu_proto_sfu_proto_rawDescGZIP(), []int{8}
}

func (x *SignalResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SignalResponse) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *SignalResponse) GetPayload() isSignalResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignalResponse) GetSdp() *SessionDescription {
	if x != nil {
		if x, ok := x.Payload.(*SignalResponse_Sdp); ok {
			return x.Sdp
		}
	}
	return nil
}

func (x *SignalResponse) GetCandidate() *IceCandidate {
	if x != nil {
		if x, ok := x.Payload.(*SignalResponse_Candidate); ok {
			return x.Candidate
		}
	}
	return nil
}

type isSignalResponse_Payload interface {
	isSignalResponse_Payload()
}

type SignalResponse_Sdp struct {
	Sdp *SessionDescription `protobuf:"bytes,3,opt,name=sdp,proto3,oneof"`
}

type SignalResponse_Candidate struct {
	Candidate *IceCandidate `protobuf:"bytes,4,opt,name=candidate,proto3,oneof"`
}

func (*SignalResponse_Sdp) isSignalResponse_Payload() {}

func (*SignalResponse_Candidate) isSignalResponse_Payload() {}

var File_internal_sfu_proto_sfu_proto protoreflect.FileDescriptor

const file_internal_sfu_proto_sfu_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/sfu/proto/sfu.proto\x12\x03sfu\"\x14\n" +
	"\x12HealthCheckRequest\"B\n" +
	"\x13HealthCheckResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"R\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\"N\n" +
	"\x12SessionDescription\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x10\n" +
	"\x03sdp\x18\x03 \x01(\tR\x03sdp\"\xae\x01\n" +
	"\fIceCandidate\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1c\n" +
	"\tcandidate\x18\x02 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x03 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x04 \x01(\x05R\rsdpMlineIndex\x12+\n" +
	"\x11username_fragment\x18\x05 \x01(\tR\x10usernameFragment\"L\n" +
	"\x04Join\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\"M\n" +
	"\x05Leave\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\"\xff\x01\n" +
	"\rSignalRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\x1f\n" +
	"\x04join\x18\x03 \x01(\v2\t.sfu.JoinH\x00R\x04join\x12+\n" +
	"\x03sdp\x18\x04 \x01(\v2\x17.sfu.SessionDescriptionH\x00R\x03sdp\x121\n" +
	"\tcandidate\x18\x05 \x01(\v2\x11.sfu.IceCandidateH\x00R\tcandidate\x12\"\n" +
	"\x05leave\x18\x06 \x01(\v2\n" +
	".sfu.LeaveH\x00R\x05leaveB\t\n" +
	"\apayload\"\xbb\x01\n" +
	"\x0eSignalResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12+\n" +
	"\x03sdp\x18\x03 \x01(\v2\x17.sfu.SessionDescriptionH\x00R\x03sdp\x121\n" +
	"\tcandidate\x18\x04 \x01(\v2\x11.sfu.IceCandidateH\x00R\tcandidateB\t\n" +
	"\apayload2\x85\x01\n" +
	"\n" +
	"SFUService\x12@\n" +
	"\vHealthCheck\x12\x17.sfu.HealthCheckRequest\x1a\x18.sfu.HealthCheckResponse\x125\n" +
	"\x06Signal\x12\x12.sfu.SignalRequest\x1a\x13.sfu.SignalResponse(\x010\x01B(Z&github.com/pion/ion/internal/sfu;protob\x06proto3"

var (
	file_internal_sfu_proto_sfu_proto_rawDescOnce sync.Once
	file_internal_sfu_proto_sfu_proto_rawDescData []byte
)

func file_internal_sfu_proto_sfu_proto_rawDescGZIP() []byte {
	file_internal_sfu_proto_sfu_proto_rawDescOnce.Do(func() {
		file_internal_sfu_proto_sfu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_sfu_proto_sfu_proto_rawDesc), len(file_internal_sfu_proto_sfu_proto_rawDesc)))
	})
	return file_internal_sfu_proto_sfu_proto_rawDescData
}

var file_internal_sfu_proto_sfu_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_sfu_proto_sfu_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),   // 0: sfu.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 1: sfu.HealthCheckResponse
	(*CreateSessionRequest)(nil), // 2: sfu.CreateSessionRequest
	(*SessionDescription)(nil),   // 3: sfu.SessionDescription
	(*IceCandidate)(nil),         // 4: sfu.IceCandidate
	(*Join)(nil),                 // 5: sfu.Join
	(*Leave)(nil),                // 6: sfu.Leave
	(*SignalRequest)(nil),        // 7: sfu.SignalRequest
	(*SignalResponse)(nil),       // 8: sfu.SignalResponse
}
var file_internal_sfu_proto_sfu_proto_depIdxs = []int32{
	5, // 0: sfu.SignalRequest.join:type_name -> sfu.Join
	3, // 1: sfu.SignalRequest.sdp:type_name -> sfu.SessionDescription
	4, // 2: sfu.SignalRequest.candidate:type_name -> sfu.IceCandidate
	6, // 3: sfu.SignalRequest.leave:type_name -> sfu.Leave
	3, // 4: sfu.SignalResponse.sdp:type_name -> sfu.SessionDescription
	4, // 5: sfu.SignalResponse.candidate:type_name -> sfu.IceCandidate
	0, // 6: sfu.SFUService.HealthCheck:input_type -> sfu.HealthCheckRequest
	7, // 7: sfu.SFUService.Signal:input_type -> sfu.SignalRequest
	1, // 8: sfu.SFUService.HealthCheck:output_type -> sfu.HealthCheckResponse
	8, // 9: sfu.SFUService.Signal:output_type -> sfu.SignalResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_sfu_proto_sfu_proto_init() }
func file_internal_sfu_proto_sfu_proto_init() {
	if File_internal_sfu_proto_sfu_proto != nil {
		return
	}
	file_internal_sfu_proto_sfu_proto_msgTypes[7].OneofWrappers = []any{
		(*SignalRequest_Join)(nil),
		(*SignalRequest_Sdp)(nil),
		(*SignalRequest_Candidate)(nil),
		(*SignalRequest_Leave)(nil),
	}
	file_internal_sfu_proto_sfu_proto_msgTypes[8].OneofWrappers = []any{
		(*SignalResponse_Sdp)(nil),
		(*SignalResponse_Candidate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_sfu_proto_sfu_proto_rawDesc), len(file_internal_sfu_proto_sfu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_sfu_proto_sfu_proto_goTypes,
		DependencyIndexes: file_internal_sfu_proto_sfu_proto_depIdxs,
		MessageInfos:      file_internal_sfu_proto_sfu_proto_msgTypes,
	}.Build()
	File_internal_sfu_proto_sfu_proto = out.File
	file_internal_sfu_proto_sfu_proto_goTypes = nil
	file_internal_sfu_proto_sfu_proto_depIdxs = nil
}
