// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: internal/sfu/proto/sfu.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SFUService_HealthCheck_FullMethodName = "/sfu.SFUService/HealthCheck"
	SFUService_Signal_FullMethodName      = "/sfu.SFUService/Signal"
)

// SFUServiceClient is the client API for SFUService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SFUServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Signal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SignalRequest, SignalResponse], error)
}

type sFUServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSFUServiceClient(cc grpc.ClientConnInterface) SFUServiceClient {
	return &sFUServiceClient{cc}
}

func (c *sFUServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, SFUService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sFUServiceClient) Signal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SignalRequest, SignalResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SFUService_ServiceDesc.Streams[0], SFUService_Signal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SignalRequest, SignalResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SFUService_SignalClient = grpc.BidiStreamingClient[SignalRequest, SignalResponse]

// SFUServiceServer is the server API for SFUService service.
// All implementations must embed UnimplementedSFUServiceServer
// for forward compatibility.
type SFUServiceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	Signal(grpc.BidiStreamingServer[SignalRequest, SignalResponse]) error
	mustEmbedUnimplementedSFUServiceServer()
}

// UnimplementedSFUServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSFUServiceServer struct{}

func (UnimplementedSFUServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedSFUServiceServer) Signal(grpc.BidiStreamingServer[SignalRequest, SignalResponse]) error {
	return status.Error(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedSFUServiceServer) mustEmbedUnimplementedSFUServiceServer() {}
func (UnimplementedSFUServiceServer) testEmbeddedByValue()                    {}

// UnsafeSFUServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SFUServiceServer will
// result in compilation errors.
type UnsafeSFUServiceServer interface {
	mustEmbedUnimplementedSFUServiceServer()
}

func RegisterSFUServiceServer(s grpc.ServiceRegistrar, srv SFUServiceServer) {
	// If the following call panics, it indicates UnimplementedSFUServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SFUService_ServiceDesc, srv)
}

func _SFUService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFUServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SFUService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFUServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SFUService_Signal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SFUServiceServer).Signal(&grpc.GenericServerStream[SignalRequest, SignalResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SFUService_SignalServer = grpc.BidiStreamingServer[SignalRequest, SignalResponse]

// SFUService_ServiceDesc is the grpc.ServiceDesc for SFUService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SFUService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sfu.SFUService",
	HandlerType: (*SFUServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _SFUService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Signal",
			Handler:       _SFUService_Signal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/sfu/proto/sfu.proto",
}
